services:
  fastapi:
    build: service/backend/
    ports:
      - 8000:8000
    networks:
      - deploy_network
    container_name: fastapi

  streamlit:
    build: service/frontend/
    depends_on:
      - fastapi
    ports:
        - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit

networks:
  deploy_network:
    driver: bridge